version: '3'

services:
  postgresdb:
    image: postgres:9.6-alpine
    container_name: postgres-container
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  api:
    container_name: api
    build:
      context: ./api/api
      dockerfile: development.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgresdb
    links:
      - postgresdb

  frontend:
    container_name: react-web
    build:
      context: ./frontend
      dockerfile: development.Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true 
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    links:
      - api